app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for

from app.tasks import add

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/home')
def home():
    return redirect(url_for('playground.get_playground'))


@main.route('/test_celery')
def test_celery():
    task = add.delay(4, 4)
    return str(task.id)

app/playground/routes.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from celery.result import AsyncResult

from app.extensions import db
from app.models import ExecutionRequest
from app.tasks import run


playground = Blueprint('playground', __name__)


@playground.route('/playground')
def get_playground():
    return render_template('playground.html', nonav=True)


@playground.route('/run', methods=['POST'])
def run_code():

    data = request.json

    lang = data['lang']
    src = data['src']

    # Create an entry in database
    req = ExecutionRequest(lang=lang, src=src, user_id=current_user.id)
    db.session.add(req)
    db.session.commit()

    # pass database id to celery task
    req_id = req.id
    task = run.apply_async(args=[req_id])

    return jsonify({"task_id": task.id}), 202


@playground.route('/status/<task_id>')
def get_status(task_id):

    task_result = AsyncResult(task_id)
    result = {
        "task_id": task_id,
        "task_status": task_result.status,
        "task_result": task_result.result
    }
    
    print(result)
    
    return jsonify(result), 200

@playground.route('/langs')
def get_langs():
    return render_template('langs.html')

@playground.route('/showcase')
def get_showcase():
    return render_template('showcase.html')

@playground.route('/security')
def get_security():
    return render_template('security.html')

@playground.route('/home')
def get_user():
    
    past_requests = current_user.requests
    
    return render_template('home.html', past_requests=past_requests)

@playground.route('/result/<req_id>')
def get_result(req_id):
    
    result = ExecutionRequest.query.filter_by(id=req_id).get_or_404()
    
    return render_template('result.html', result = result)

app/users/routes.py
from flask import (Blueprint, abort, flash, redirect, render_template, request,
                   url_for)
from flask_login import current_user, login_required, login_user, logout_user
from app.extensions import bcrypt, db
from app.models import User

from app.users.forms import (LoginForm, RegistrationForm,
                             UpdateAccountForm, ResetPasswordRequestForm, ResetPasswordForm)
from app.users.utils import save_picture
#from app.users.email import send_password_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(username=form.username.data,
                    email=form.email.data)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash(
            f"Account successfuly created for {form.username.data}", "success")

        return redirect(url_for('users.login'))

    return render_template('register.html', form=form, nonav=True)


@users.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)

            # this route when user was redirected from a page to login
            # we are sending the user back to that page
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', form=form, nonav=True)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateAccountForm()

    if form.validate_on_submit():

        if form.picture.data:
            picture_file = save_picture(form.picture.data)  # return file name
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()

        flash('Your account has been updated!', 'success')

        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    #image_file = current_user.get_avatar()
    # print(image_file)

    return render_template('account.html', title=current_user.username, nonav=True, form=form)


""" @users.route('/reset-password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            print('User Requesting password rest exists .')
            send_password_reset_email(user)
            print('Email Sent to user .')

        flash('Check your email for the instructions to reset your password')
        return redirect(url_for('users.login'))

    return render_template('reset_password_request.html',
                           title='Reset Password', form=form)


@users.route('/reset-password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.new_password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    
    return render_template('reset_password.html', form=form)
 """
""" 
@users.route('/user/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user).order_by(
        Post.date_created.desc()).paginate(per_page=5, page=page)

    return render_template('user_posts.html', user=user, posts=posts) """

app/templates/index.html
{% extends 'layout.html'%} {% block content %}

<style>
  .banner {
    margin-top: 2rem;
    margin-bottom: 2rem;
    background-color: #fe5167;
  }

  .banner-text-container {
    height: 600px;
  }

  .banner-img-container {
    height: 600px;
  }
</style>

<div class="container banner">
  <div class="row">
    <div class="col">
      <div class="container banner-text-container">
        <div class="container" style="height: 100px"></div>
        <div class="container banner-text">
          <p class="display-1 font-weight-bold" style="font-weight: 900">
            Sailor
          </p>
          <p class="display-6">
            Secure <br />
            Online <br />
            Compiler <br />
          </p>
          <a
            href="{{url_for('users.login')}}"
            class="btn btn-dark m-1"
            style="width: 100%"
            >Login</a
          >
          <a
            href="{{url_for('users.register')}}"
            class="btn btn-outline-light m-1"
            style="width: 100%"
            >Register</a
          >
        </div>
      </div>
    </div>
    <div class="col-8">
      <div class="container banner-img-container d-flex">
        <img
          src="{{url_for('static', filename='images/processor.png')}}"
          alt=""
          class="img-fluid my-auto"
        />
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" style="height: 200px"></div>

<div class="container my-2">
  <div class="row">
    <div class="col">
      <div
        class="container mx-auto"
        style="background-color: #fe5167; height: 500px; width: 400px"
      ></div>
    </div>
    <div class="col">
      <img
        src="{{url_for('static',filename='images/Saly-38.png')}}"
        class="img-fluid"
        alt=""
      />
    </div>
  </div>
</div>

<div class="container m-2">
  <div class="row">
    <div class="col">
      <img
        src="{{url_for('static',filename='images/Saly-39.png')}}"
        class="img-fluid"
        alt=""
        style="height: 500px"
      />
    </div>
    <div class="col">
      <div
        class="container mx-auto"
        style="background-color: #fe5167; height: 500px; width: 400px"
      ></div>
    </div>
  </div>
</div>

<div class="container my-4">
  <div class="row">
    <div class="col">
      <div
        class="container mx-auto"
        style="background-color: #fe5167; height: 500px; width: 400px"
      ></div>
    </div>
    <div class="col">
      <img
        src="{{url_for('static',filename='images/Saly-40.png')}}"
        class="img-fluid"
        alt=""
        style="height: 500px"
      />
    </div>
  </div>
</div>

<div class="container-fluid" style="height: 200px"></div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="container" style="height: 100px"></div>
      <div class="container mx-auto" style="width: 300px">
        <p class="display-1" style="font-weight: 900">
          you're <br />
          in <br />
          control
        </p>
      </div>
    </div>

    <div class="col">
      <img
        src="{{url_for('static',filename='images/Saly-8.png')}}"
        class="img-fluid"
        alt=""
      />
    </div>
  </div>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% if title %}
    <title>{{title}} - Sailor</title>
    {% else %}
    <title>Sailor - Secure Online Compiler</title>
    {% endif %}

    <!-- Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300&display=swap"
      rel="stylesheet"
    />

    <!-- CSS -->
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='styles/main.css')}}"
    />

    <!-- Jquery -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
      integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
  </head>

  <body>
    {% with messages = get_flashed_messages(with_categories=True) %} {% if
    messages %} {% for category, message in messages %}
    <div class="alert alert-{{category}} mb-0">{{message}}</div>
    {% endfor %} {% endif %} {% endwith %} {% if nonav == NULL %}

    <nav class="navbar main-nav navbar-expand-sm navbar-dark">
      <div class="container">
        <a class="navbar-brand" href="{{url_for('main.home')}}">
          <span style="font-weight: 900">Sailor</span>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">@{{current_user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.logout')}}">logout</a>
            </li>

            {% else %}
            <li class="nav-item">
              <a
                class="nav-link btn btn-outline-light"
                href="{{url_for('users.login')}}"
                style="margin: 4px"
                >Login</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link btn btn-outline-dark"
                style="margin: 4px"
                href="{{url_for('users.register')}}"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% endif %} {% block content %} {% endblock %}
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %} {% block content %}

<style>
  .shadow-container {
    box-shadow: 2.8px 2.8px 2.2px rgba(0, 0, 0, 0.02),
      6.7px 6.7px 5.3px rgba(0, 0, 0, 0.028),
      12.5px 12.5px 10px rgba(0, 0, 0, 0.035),
      22.3px 22.3px 17.9px rgba(0, 0, 0, 0.042),
      41.8px 41.8px 33.4px rgba(0, 0, 0, 0.05),
      100px 100px 80px rgba(0, 0, 0, 0.07);
  }

  .login-btn {
    width: 100%;
  }

  .login-btn:hover {
    background-color: white;
    color: grey;
    font-weight: bold;
  }
</style>

<style>

</style>

<div class="container-fluid my-4">
  <div class="row">
    <div class="col">
      <img
        src="{{url_for('static', filename='images/Saly-1.png')}}"
        class="img-fluid"
        alt=""
      />
    </div>
    <div class="col d-flex">
      <div class="card form-card shadow-container">
        <div class="card-body content-section">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Log In</legend>
              <div class="form-group">
                {{ form.email.label(class="form-control-label") }} {% if
                form.email.errors %} {{ form.email(class="form-control
                is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control ") }} {% endif %}
              </div>
              <div class="form-group">
                {{ form.password.label(class="form-control-label") }} {% if
                form.password.errors %} {{ form.password(class="form-control
                is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
                {% else %} {{ form.password(class="form-control ") }} {% endif
                %}
              </div>
              <div class="form-check mt-2">
                {{ form.remember(class="form-check-input") }} {{
                form.remember.label(class="form-check-label") }}
              </div>
            </fieldset>
            <div class="form-group my-2">
              {{ form.submit(class="btn btn-secondary login-btn") }}
            </div>
            <small class="text-muted ml-2">
              <a href="#">Forgot Password?</a>
            </small>
          </form>
        </div>
        <div class="card-footer border-top pt-3">
          <small class="text-muted">
            Need An Account?
            <a class="ml-2" href="{{ url_for('users.register') }}"
              >Sign Up Now</a
            >
          </small>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/templates/playground.html
{% extends "layout.html" %} {% block content %}

<style>
  .code-editor {
    font-family: "Courier New", Courier, monospace;
    font-size: large;
    width: 100%;
    height: 600px;
    border-radius: 5px;
    scrollbar-width: thin;
    box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.034),
      0 6.7px 5.3px rgba(0, 0, 0, 0.048), 0 12.5px 10px rgba(0, 0, 0, 0.06),
      0 22.3px 17.9px rgba(0, 0, 0, 0.072), 0 41.8px 33.4px rgba(0, 0, 0, 0.086),
      0 100px 80px rgba(0, 0, 0, 0.12);
  }

  .code-editor::-webkit-scrollbar {
    width: 0;
  }

  .banner-container {
    background-repeat: no-repeat;
    background-size: contain;
    width: 500px;
    height: 600px;
  }

  .stdout-container {
    background-color: #fff2dd;
    background-color: #2f2f35;
    color: white;
    font-family: "Courier New", Courier, monospace;
    font-weight: 700;
    height: 500px;
    width: 400px;
    box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.034),
      0 6.7px 5.3px rgba(0, 0, 0, 0.048), 0 12.5px 10px rgba(0, 0, 0, 0.06),
      0 22.3px 17.9px rgba(0, 0, 0, 0.072), 0 41.8px 33.4px rgba(0, 0, 0, 0.086),
      0 100px 80px rgba(0, 0, 0, 0.12);
  }

  .stderr-container {
    background-color: #fff2dd;
    background-color: #2f2f35;
    color: crimson;
    font-family: "Courier New", Courier, monospace;
    font-weight: 700;
    height: 500px;
    width: 400px;
    box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.034),
      0 6.7px 5.3px rgba(0, 0, 0, 0.048), 0 12.5px 10px rgba(0, 0, 0, 0.06),
      0 22.3px 17.9px rgba(0, 0, 0, 0.072), 0 41.8px 33.4px rgba(0, 0, 0, 0.086),
      0 100px 80px rgba(0, 0, 0, 0.12);
  }

  .output-para {
    word-break: break-all;
    overflow: auto;
  }
</style>

<style>
  .code-editor {
    font-family: "Courier New", Courier, monospace;
    font-size: large;
    width: 500px;
    height: 600px;
    border-radius: 5px;
    scrollbar-width: thin;
  }

  .code-editor::-webkit-scrollbar {
    width: 0;
  }

  .banner-container {
    background-repeat: no-repeat;
    background-size: contain;
    width: 500px;
    height: 600px;
  }

  .stdout-container {
    font-family: "Courier New", Courier, monospace;
    height: 500px;
    width: 400px;
    background-color: #2f2f35;
    box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.034),
      0 6.7px 5.3px rgba(0, 0, 0, 0.048), 0 12.5px 10px rgba(0, 0, 0, 0.06),
      0 22.3px 17.9px rgba(0, 0, 0, 0.072), 0 41.8px 33.4px rgba(0, 0, 0, 0.086),
      0 100px 80px rgba(0, 0, 0, 0.12);
  }

  .stderr-container {
    font-family: "Courier New", Courier, monospace;
    height: 500px;
    width: 400px;
    background-color: #2f2f35;
    box-shadow: 0 2.8px 2.2px rgba(0, 0, 0, 0.034),
      0 6.7px 5.3px rgba(0, 0, 0, 0.048), 0 12.5px 10px rgba(0, 0, 0, 0.06),
      0 22.3px 17.9px rgba(0, 0, 0, 0.072), 0 41.8px 33.4px rgba(0, 0, 0, 0.086),
      0 100px 80px rgba(0, 0, 0, 0.12);
  }
</style>

<style>
  .typewriter {
    display: inline-block;
  }
  .typewriter h1 {
    overflow: hidden; /* Ensures the content is not revealed until the animation */

    white-space: nowrap; /* Keeps the content on a single line */
    margin: 0 auto; /* Gives that scrolling effect as the typing happens */
    letter-spacing: 0.15em; /* Adjust as needed */
    animation: typing 3.5s steps(40, end), blink-caret 0.75s step-end infinite;
  }

  /* The typing effect */
  @keyframes typing {
    from {
      width: 0;
    }
    to {
      width: 100%;
    }
  }

  /* The typewriter cursor effect */
  @keyframes blink-caret {
    from,
    to {
      border-color: transparent;
    }
    50% {
      border-color: orange;
    }
  }
</style>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
  <path
    fill="#fe5167"
    fill-opacity="1"
    d="M0,0L16,26.7C32,53,64,107,96,122.7C128,139,160,117,192,117.3C224,117,256,139,288,128C320,117,352,75,384,69.3C416,64,448,96,480,122.7C512,149,544,171,576,154.7C608,139,640,85,672,74.7C704,64,736,96,768,117.3C800,139,832,149,864,149.3C896,149,928,139,960,128C992,117,1024,107,1056,112C1088,117,1120,139,1152,133.3C1184,128,1216,96,1248,101.3C1280,107,1312,149,1344,144C1376,139,1408,85,1424,58.7L1440,32L1440,0L1424,0C1408,0,1376,0,1344,0C1312,0,1280,0,1248,0C1216,0,1184,0,1152,0C1120,0,1088,0,1056,0C1024,0,992,0,960,0C928,0,896,0,864,0C832,0,800,0,768,0C736,0,704,0,672,0C640,0,608,0,576,0C544,0,512,0,480,0C448,0,416,0,384,0C352,0,320,0,288,0C256,0,224,0,192,0C160,0,128,0,96,0C64,0,32,0,16,0L0,0Z"
  ></path>
</svg>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="container text-center typewriter">
        <h1 class="display-1">Sailor...|</h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <div class="btn-container my-2">
        <fieldset class="d-flex flex-row">
          <button
            id="runBtn"
            class="btn btn-outline-light"
            type="button"
            style="
              margin: 0px;
              width: 100px;
              margin-left: 0px;
              margin-right: 16px;
            "
          >
            <i class="fa fa-caret-right"></i>
            <!-- <i class="fa fa-circle-o-notch fa-spin"></i> -->
            Run
          </button>
          <select
            id="langSelect"
            class="form-select ms-auto"
            style="margin-right: 0px; width: 200px"
            name="Select Language"
          >
            <option selected value="cpp">C++</option>
            <option value="c">C</option>
            <option value="py">Python</option>
            <option value="js">JavaScript</option>
          </select>
        </fieldset>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div
        class="container"
        id="codeEditor"
        style="height: 600px; font-size: 18px"
      ></div>
    </div>
  </div>
</div>
<div class="container">
  <div class="container" style="height: 200px"></div>
  <div class="row" id="results">
    <div class="col">
      <div class="container" style="height: 100px"></div>
      <div class="card stdout-container mx-auto">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#00C897"
            fill-opacity="1"
            d="M0,288L48,277.3C96,267,192,245,288,218.7C384,192,480,160,576,170.7C672,181,768,235,864,224C960,213,1056,139,1152,144C1248,149,1344,235,1392,277.3L1440,320L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"
          ></path>
        </svg>
        <div class="card-body">
          <p>stdout></p>
          <p id="stdout"></p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card stderr-container mx-auto">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#DC143C"
            fill-opacity="1"
            d="M0,288L48,277.3C96,267,192,245,288,218.7C384,192,480,160,576,170.7C672,181,768,235,864,224C960,213,1056,139,1152,144C1248,149,1344,235,1392,277.3L1440,320L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"
          ></path>
        </svg>
        <div class="card-body">
          <p>stderr></p>
          <p id="stderr"></p>
        </div>
        <div class="container" style="height: 100px"></div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <img
        src="{{url_for('static', filename='images/Saly-10.png')}}"
        alt=""
        class="img-fluid"
      />
    </div>
  </div>
</div>

<script
  src="{{url_for('static', filename='vendor/ace-builds/src-noconflict/ace.js')}}"
  type="text/javascript"
  charset="utf-8"
></script>
<script>
  $(document).ready(function () {
    var editor = ace.edit("codeEditor");
    editor.setTheme("ace/theme/twilight");
    editor.session.setMode("ace/mode/c_cpp");
    editor.setValue("", -1);

    let langSelector = $("#langSelect");

    let langSelect = $("#langSelect :selected");
    console.log("lang in select : ", langSelect.val());
    let runBtn = $("#runBtn");

    langSelector.on("change", () => {
      let langSelect = $("#langSelect :selected");
      console.log("lang in select : ", langSelect.val());
      switch (langSelect.val()) {
        case "cpp":
          editor.session.setMode("ace/mode/c_cpp");
          break;
        case "c":
          editor.session.setMode("ace/mode/c_cpp");
          break;
        case "py":
          editor.session.setMode("ace/mode/python");
          break;
        case "py":
          editor.session.setMode("ace/mode/javascript");
          break;
      }
    });

    function handleClick(lang, src) {
      console.log("Making a POST fetch request...");

      fetch("/run", {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          lang: lang,
          src: src,
        }),
      })
        .then((response) => response.json())
        .then((data) => getStatus(data.task_id));
    }

    function getStatus(taskID) {
      console.log("ping...Is my job done?");
      fetch(`/status/${taskID}`, {
        method: "GET",
        credentials: "include",
        headers: {
          "Content-Type": "application/json",
        },
      })
        .then((response) => response.json())
        .then((res) => {
          // do something with result

          document.getElementById("results").scrollIntoView({
            behavior: "smooth",
          });

          const taskStatus = res.task_status;

          if (taskStatus === "SUCCESS") {
            const taskResult = res.task_result;

            console.log("returncode : ", taskResult.returncode);
            console.log("stdout : ", taskResult.stdout);
            console.log("stderr : ", taskResult.stderr);

            let stdout = $("#stdout");
            let stderr = $("#stderr");

            stdout.text(taskResult.stdout);
            stderr.text(taskResult.stderr);
          }

          if (taskStatus === "SUCCESS" || taskStatus === "FAILURE")
            return false;

          setTimeout(function () {
            getStatus(res.task_id);
          }, 1000);
        })
        .catch((err) => console.log(err));
    }

    runBtn.on("click", function () {
      console.log("Run Button was clicked");

      let langSelect = $("#langSelect :selected");
      let lang = langSelect.val();
      let src = editor.getValue();

      console.log("lang :", lang);
      console.log("src :", src);

      handleClick(lang, src);
    });
  });
</script>
<script src=""></script>
{% endblock content %}